// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import axiosClient from '@/lib/axios';

import type {
  ApiResponse,
} from '@/types';
import type {
  AddToCartRequest,
  CartItemResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── CartService ──────────────────────────────────────────────
export const CartService = {

  async getCart(config?: AxiosRequestConfig): Promise<ApiResponse<CartItemResponse[]>> {
    const { data } = await axiosClient.get('/api/v1/cart', config);
    return data;
  },

  async addToCart({ body }: { body: AddToCartRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.post('/api/v1/cart', body, config);
    return data;
  },

  async removeFromCart({ itemId }: { itemId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.delete(`/api/v1/cart/${itemId}`, config);
    return data;
  },

  async clearCart(config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.delete('/api/v1/cart/clear', config);
    return data;
  },
};
