// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import axiosClient from '@/lib/axios';

import type {
  ApiResponse,
} from '@/types';
import type {
  VNPayIPNResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── PaymentService ──────────────────────────────────────────────
export const PaymentService = {

  async createCheckoutLink({ paymentId, paymentMethod }: { paymentId: string; paymentMethod: string }, config?: AxiosRequestConfig): Promise<ApiResponse<string>> {
    const { data } = await axiosClient.post(`/api/v1/payments/${paymentId}/checkout-link`, undefined, { params: { paymentMethod }, ...config });
    return data;
  },

  async handleStripeWebhook({ body }: { body: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.post('/api/v1/payments/stripe-webhook', body, config);
    return data;
  },

  async handleMoMoCallback({ body }: { body: Record<string, string> }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.post('/api/v1/payments/momo-callback', body, config);
    return data;
  },

  async handleVNPayIPN(config?: AxiosRequestConfig): Promise<VNPayIPNResponse> {
    const { data } = await axiosClient.get('/api/v1/payments/IPN', config);
    return data;
  },
};
