// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import axiosClient from '@/lib/axios';

import type {
  ApiResponse,
} from '@/types';
import type {
  PaymentRequest,
  PaymentResponse,
  VNPayIPNResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── PaymentService ──────────────────────────────────────────────
export const PaymentService = {

  async cancelPayment({ orderId, paymentMethod }: { orderId: string; paymentMethod: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PaymentResponse>> {
    const { data } = await axiosClient.put('/api/v1/payments/cancel', undefined, { params: { orderId, paymentMethod }, ...config });
    return data;
  },

  async requestMomoPayment({ body }: { body: PaymentRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<string>> {
    const { data } = await axiosClient.post('/api/v1/payments', body, config);
    return data;
  },

  async handleMoMoCallback({ body }: { body: Record<string, string> }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await axiosClient.post('/api/v1/payments/momo-callback', body, config);
    return data;
  },

  async handleVNPayIPN(config?: AxiosRequestConfig): Promise<VNPayIPNResponse> {
    const { data } = await axiosClient.get('/api/v1/payments/IPN', config);
    return data;
  },
};
