// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import { CourseResponse } from "./course";

// ── Domain types ───────────────────────────────────────────────

export interface AddToCartRequest {
  courseId: string;
}

export interface CartItemResponse {
  id?: string;
  course?: CourseResponse;
}
