// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

// ── Domain types ───────────────────────────────────────────────

export interface AddToCartRequest {
  courseId: string;
}

export interface CartItemResponse {
  id?: string;
  course?: CourseResponse;
}

export interface CategoryResponse {
  id?: string;
  name?: string;
}

export interface CourseImageResponse {
  id?: string;
  imageUrl?: string;
}

export interface CourseResponse {
  id?: string;
  title?: string;
  description?: string;
  category?: CategoryResponse;
  instructor?: InstructorResponse;
  images?: CourseImageResponse[];
  price?: number;
  discountedPrice?: number;
  discountRate?: number;
  rating?: number;
  enrollmentCount?: number;
  isInSubscription?: boolean;
  duration?: number;
  status?: string;
  publishStatus?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface InstructorResponse {
  id?: string;
  name?: string;
  email?: string;
  bio?: string;
  profilePictureUrl?: string;
}
