// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

// ── Domain types ───────────────────────────────────────────────

export interface UserNotificationResponse {
  id?: string;
  userId?: string;
  title?: string;
  message?: string;
  isRead?: boolean;
}
