// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

// ── Domain types ───────────────────────────────────────────────

export interface PaymentResponse {
  id?: string;
  orderId?: string;
  amount?: number;
  status?: "PROCESSING" | "PAID" | "CANCELLED" | "REFUNDED";
  paymentDate?: string;
  paymentInfo?: string;
  paymentMessage?: string;
}

export interface PaymentRequest {
  orderId: string;
  paymentMethod: "VN_PAY" | "MOMO";
}

export interface VNPayIPNResponse {
  RspCode?: string;
  Message?: string;
}
